### PR TITLE
Fix issue with loading error templates for specific error codes.

### PR DESCRIPTION
**Pull request by ruslan5t**
Please see - https://github.com/PebbleTemplates/pebble-spring-boot-starter/issues/10.

### CODE REVIEW

**Comment by hectorlf** [comment]
Thanks for spotting this! To be honest, at the beginning I wasn´t really sure on if/what the TemplateAvailabilityProvider was used for, so I just based it off the Thymeleaf one. Wow, was I wrong...

Having said that, the issue now is that we offer the option to use customized Pebble Loaders and hardcoding a classpath resource may not work 100% of the time. Well... 50% of the time is better than the current 0% percent...

The inflexibility of the TemplateAvailabilityProvider doesn´t help either. Any suggestions?

**Comment by ruslan5t** [comment]
Hey Héctor!

Unfortunately I am not very familiar with pebble inner implementation, just started to use it a week ago, so probably my opinion will not be very useful for you. Based on what I see, it is a little bit different from thymeleaf/freemarker/groovy templates implementation, especially this TemplateAvailabilityProvider, it looks like other template engines use almost same implementation (with "classpath:" hardcorded as part of template prefix), I tried to make it same for pebble, but unfortunately other errors appeared and I was not able to fix them. I think the only thing that I can do without breaking anything else now is adding additional property especially for this TemplateAvailabilityProvider, so user will be able to change directory especially for it, but I am not sure, maybe it is not useful at all for customized pebble loaders.

By the way - thanks for this tool, it looks like pebble is the best thing that can be used for non SPA applications with spring boot now - apache tiles and jsp are outdated and require container as tomcat, thymeleaf has ugly layout system (inheritance, nesting), groovy templates are not supported in any IDE (even plugins don't exist), freemarker is very simplified tool and cannot be used for something difficult, other template engines also have its own downsides. On other sides pebble has excellent layout system (inheritance + nesting), with configured twig plugin it has excellent support in intellij idea and it has its own spring boot starter :+1: The only bad thing about it that it is not promoted anywhere.

**Comment by ruslan5t** [comment]
Can we merge this pull request?

**Comment by hectorlf** [comment]
It´ll have to do for the time being, at least it´ll fix the common use case.

Thanks for the kind words, but the real mastermind behind Pebble is @mbosecke, I only maintain the starter!

**Comment by hectorlf** [comment]
Speaking of which, the Starter releases are tied to core Pebble releases, so I´m going to invoke @mbosecke to coordinate. Thank you very much!

**Pull request merged**
